### ISSUE TITLE
Integration module company

### ISSUE THREAD

**Issue by NathaelB** [placecare/backend#2]
We need to add the management of facilities (EHPAD) in our API REST to store and manage specific information for each facility. This will help distinguish between different entities and facilitate the management of patients and healthcare professionals within each facility.

## Tasks to be completed
- [x] Create the `company` data model
    - Attributes
        - `id` : Unique identifier for the facility
        - `name` : Name of the facility
        - `address` (Object)
        - `contact` (Object)
        - `siret_number`: SIRET number of the company
        - `approval_number` Approval number (if applicable)
- [x] Create REST Endpoints for `Company`
   - [x] `POST /companies` : Create a new company
   - [x] `GET /companies` : Retrieve a list of all company
   - [x] `GET /companies/{id}` : Retrieve details of a specific company
   - [x] `PUT /companies/{id}`
   - [x] `DELETE /companies/{id}`

- [x] Validation and data security
     - Implement validation to ensure required data is present and properly formatted
     - Secure the endpoints, to ensure only authorized users can create, update, or delete companies
- [x] Unit and Integration Testing
   - Create tests to verify the correct functionality of each endpoint.
   - Ensure validations work correctly and errors are handled appropriately.

## Acceptance Criteria:
- The `Company` model is properly integrated and documented.
- All REST endpoints function as expected and pass unit and integration tests.
- Data validation and security are in place.

**Comment by NathaelB** [comment]
I have a question @LeadcodeDev , for the `siret` & `approvalNumber` columns, do the fields have to be unique ?
